services:
  event-management-db:
    image: postgres:18.3
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event-management
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  redis:
    image: redis:8.6.2
    ports:
      - "6379:6379"

  event-management-api:
    build:
      context: ./event-management/
    ports:
      - "8080:8080"
    depends_on:
      - event-management-db
      - redis
    environment:
      POSTGRES_HOST: event-management-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: main
      POSTGRES_PASSWORD: password
      POSTGRES_DBNAME: event-management
      POSTGRES_SSLMODE: disable
      POSTGRES_TIMEZONE: UTC
      POSTGRES_MAX_OPEN_CONNS: 25
      POSTGRES_CONN_MAX_LIFETIME: 300
      POSTGRES_MAX_IDLE_CONNS: 10
      POSTGRES_CONN_MAX_IDLE_TIME: 60
      SERVER_MODE: development
      SERVER_ADDR: ":8080"
      SERVER_READ_TIMEOUT: 10
      SERVER_WRITE_TIMEOUT: 10
      SERVER_MAX_HEADER_BYTES: 1048576
      SERVER_CTX_TIMEOUT: 30
      REDIS_ADDR: localhost:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0

volumes:
  db_data:
