-- +goose Up
CREATE TABLE IF NOT EXISTS events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uuid TEXT NOT NULL UNIQUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	venue_id BIGINT NOT NULL,
	date TIMESTAMPTZ NOT NULL,
	name TEXT NOT NULL,
	description TEXT,
	CONSTRAINT fk_events_venue FOREIGN KEY (venue_id)
		REFERENCES venues (id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_events_venue_id ON events (venue_id);
CREATE INDEX IF NOT EXISTS idx_events_date ON events (date);
CREATE INDEX IF NOT EXISTS idx_events_name ON events (name);

-- +goose Down
DROP TABLE IF EXISTS events;
