-- +goose Up
CREATE TABLE IF NOT EXISTS tickets (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uuid TEXT NOT NULL UNIQUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	event_id BIGINT NOT NULL,
	price BIGINT NOT NULL CHECK (price >= 0),
	seat TEXT NOT NULL,
	status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'booked')),
	CONSTRAINT fk_tickets_event FOREIGN KEY (event_id)
		REFERENCES events (id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_tickets_event_id ON tickets (event_id);
CREATE INDEX IF NOT EXISTS idx_tickets_seat ON tickets (seat);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets (status);

-- +goose Down
DROP TABLE IF EXISTS tickets;
