-- +goose Up
CREATE TABLE IF NOT EXISTS performers (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uuid TEXT NOT NULL UNIQUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	age BIGINT NOT NULL CHECK (age >= 0),
	name TEXT NOT NULL,
	description TEXT
);

CREATE INDEX IF NOT EXISTS idx_performers_name ON performers (name);

-- +goose Down
DROP TABLE IF EXISTS performers;
